services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: facebook_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - facebook_management_pgdata:/var/lib/postgresql/data

volumes:
  facebook_management_pgdata:
